server:
  port: 8082

spring:
  application:
    name: Compare
  data:
    mongodb:
      uri: mongodb+srv://sdutta:A8T4bruLnXSdhuPc@multikart.khko0j6.mongodb.net/multikart_compare?retryWrites=true&w=majority

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
