server:
  port: 8086

spring:
  application:
    name: Order
  data:
    mongodb:
      uri: mongodb+srv://sdutta:A8T4bruLnXSdhuPc@multikart.khko0j6.mongodb.net/multikart_order?retryWrites=true&w=majority


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka





